ExpProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('costless/', include('costless.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

costless/urls.py
from django.urls import path

from . import views

app_name = 'costless'
urlpatterns = [
    path('myexpenses/', views.ExpensesByUserListView.as_view(), name='my-expenses'),
    path('newexpense/', views.NewExpenseView.as_view(), name='new-expense'),
    path('mycategories/', views.ExpensesByCategoryListView.as_view(), name='my-categories'),
    path('bydate/', views.ExpensesByDateListView.as_view(), name='by-dates'),
    path('category/<str:catName>/', views.CategoryListView.as_view(), name='category'),
    path('subcategory/<str:subCatName>/', views.SubCategoryListView.as_view(), name='subcategory'),
]

accounts/models.py
from django.db import models

# Create your models here.

costless/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Category(models.Model):
    catName = models.CharField(max_length=50)

    def __str__(self):
        return self.catName


class SubCategory(models.Model):
    subCatName = models.CharField(max_length=50)

    def __str__(self):
        return self.subCatName


class Expense(models.Model):
    cost = models.IntegerField(default = 0)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcat = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    createdOn = models.DateTimeField()

    def __str__(self):
        return f'{self.cost} {self.cat} {self.subcat}'

    def was_added_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.createdOn <= now

    def get_absolute_url(self):
        return reverse('costless:my-expenses')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

costless/views.py
from django.shortcuts import render
from .models import Expense
from django.views import generic
from django.db.models import F
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import *

class ExpensesByUserListView(LoginRequiredMixin, generic.ListView):
    model = Expense
    template_name = 'costless/expenses_by_user.html'
    paginate_by = 10
    context_object_name = 'context'

    def get_context_data(self):
        latest_expenses_list = Expense.objects.filter(user=self.request.user).order_by('createdOn')
        s = 0
        for q in latest_expenses_list:
            s += q.cost
        context = {'latest_expenses_list': latest_expenses_list, 's': s}
        return context

class ExpensesByCategoryListView(LoginRequiredMixin, generic.ListView):
    model = Expense
    template_name = 'costless/expenses_by_cat.html'
    paginate_by = 10
    context_object_name = 'context'

    def get_context_data(self):
        latest_expenses_list = Expense.objects.filter(user=self.request.user)
        categories = set(q.cat.catName for q in latest_expenses_list)
        cat_list = []
        all = 0
        for c in categories:
            s = 0
            cat_exp = latest_expenses_list.filter(cat__catName = c)
            for q in cat_exp:
                s += q.cost
            cat_list.append((c, cat_exp, s))
            all += s
        context = {'cat_list': cat_list, 'all': all }
        return context

class ExpensesByDateListView(LoginRequiredMixin, generic.ListView):
    model = Expense
    template_name = 'costless/expenses_by_date.html'
    paginate_by = 10
    context_object_name = 'context'

    def get_context_data(self):
        latest_expenses_list = Expense.objects.filter(user=self.request.user)
        dates = set(q.createdOn.month for q in latest_expenses_list)
        date_list = []
        months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
        all = 0
        for d in dates:
            s = 0
            date_exp = latest_expenses_list.filter(createdOn__month=d)
            for q in date_exp:
                s += q.cost
            date_list.append((months[d-1], date_exp, s))
            all += s
        context = {'date_list': date_list, 'all': all }
        return context

class CategoryListView(LoginRequiredMixin, generic.ListView):
    model = Expense
    template_name = 'costless/category.html'
    paginate_by = 10
    context_object_name = 'context'

    def get_context_data(self):
        level = self.kwargs.get('catName')
        latest_expenses_list = Expense.objects.filter(user=self.request.user).filter(cat__catName = level)
        s = 0
        for q in latest_expenses_list:
            s += q.cost
        context = {'cat_list': latest_expenses_list, 'all': s, 'level':level}
        return context

class SubCategoryListView(LoginRequiredMixin, generic.ListView):
    model = Expense
    template_name = 'costless/subcategory.html'
    paginate_by = 10
    context_object_name = 'context'

    def get_context_data(self):
        level = self.kwargs.get('subCatName')
        latest_expenses_list = Expense.objects.filter(user=self.request.user).filter(subcat__subCatName = level)
        s = 0
        for q in latest_expenses_list:
            s += q.cost
        context = {'cat_list': latest_expenses_list, 'all': s, 'level':level}
        return context

class NewExpenseView(LoginRequiredMixin, CreateView):
    model = Expense
    template_name = 'costless/newexpense.html'
    fields = ['cost', 'cat', 'subcat', 'createdOn']
    initial = {'createdOn': datetime.now()}

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

# class IndexView(generic.ListView):
#     template_name = 'costless/expenses_by_user.html'
#     context_object_name = 'latest_expenses_list'
#     def get_queryset(self):
#         return Expense.objects.order_by('-createdOn')[:5]

        # latest_expenses_list = Expense.objects.order_by('-createdOn')[:5]
        # output = ', '.join([str(q.cat) for q in latest_expenses_list])
        # s = 0
        # for q in latest_expenses_list:
        #     s += q.cost
        # context = {'latest_expenses_list':latest_expenses_list, 's':s}
        # return render(request, 'costless/expenses_by_user.html',context)

# def stats_Cat(request, catName):
#     latest_expenses_list = Expense.objects.order_by('-createdOn')[:5]
#     latest_cat_list_by_id = [q for q in latest_expenses_list if q.cat.catName == catName]
#     s = 0
#     for q in latest_cat_list_by_id:
#         s += q.cost
#     context = {'latest_cat_list_by_id': latest_cat_list_by_id, 's':s}
#     return render(request, 'costless/expenses_by_cat.html', context)

# def stats_subCat(request, catName, subCatName):
#     latest_expenses_list = Expense.objects.order_by('-createdOn')[:5]
#     latest_subcat_list_by_id = [q for q in latest_expenses_list if q.subcat.subCatName == subCatName]
#     s = 0
#     for q in latest_subcat_list_by_id:
#         s += q.cost
#     context = {'latest_subcat_list_by_id': latest_subcat_list_by_id, 's': s}
#     return render(request, 'costless/category.html', context)

costless/templates/costless/category.html
{% extends "base.html" %}

{% block title %}Naslov{% endblock %}

{% block content %}
    {% if cat_list %}
        <p class="link"> Total for {{ level }}: {{all}} </p>
        <table class = 'styled-table'>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Subcategory</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for exp in cat_list %}
                    <tr>
                        <td>{{ exp.createdOn.date}}</td>
                        <td>{{ exp.createdOn|time}}</td>
                        <td><a href="{% url 'costless:subcategory' exp.subcat.subCatName %}">{{exp.subcat.subCatName }}</a></td>
                        <td>{{ exp.cost}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="link"><a href="{% url 'home' %}">Home</a></p>
        <p class="link"><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>No costs are available.</p>
    {% endif %}
{% endblock %}

costless/templates/costless/expenses_by_cat.html
{% extends "base.html" %}

{% block title %}Naslov{% endblock %}



{% block content %}
    <br>
    {% if cat_list %}
        <p class="link"> Total: {{all}} </p>
        <table class = 'styled-table'>
            {% for n, list, s in cat_list %}
                <thead>
                    <tr>
                        <th colspan = "3">All costs in <a href="{% url 'costless:category' n %}":>{{ n }}</a></th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in list %}
                        <tr>
                            <td>{{ e.createdOn.date}}</td>
                            {% load tz %}
                            <td>{{ e.createdOn|time }}</td>
                            <td>{{ e.cost }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan = "2">Total:</td>
                        <td>{{ s }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
        <p class="link"><a href="{% url 'home' %}">Home</a></p>
        <p class="link"><a href="{% url 'costless:new-expense' %}">Enter new expense</a></p>
        <p class="link"><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>No costs are available.</p>
    {% endif %}
{% endblock %}

costless/templates/costless/expenses_by_date.html
{% extends "base.html" %}

{% block title %}Naslov{% endblock %}

{% block content %}
    <br>
    {% if date_list %}
        <p class="link"> Total: {{all}} </p>
        <table class = 'styled-table'>
            {% for n, list, s in date_list %}
                <thead>
                    <tr>
                        <th>All costs in {{ n }}:</th>
                    </tr>
                </thead>
                <tbody>
                        {% for e in list %}
                            <tr>
                                <td>{{ e.createdOn.date}}</td>
                                <td>{{ e.createdOn|time}}</td>
                                <td>{{ e.cost }}</td>
                            </tr>
                        {% endfor %}
                    <tr>
                        <td colspan = "2">Total:</td>
                        <td>{{ s }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
        <p class="link"><a href="{% url 'home' %}">Home</a></p>
        <p class="link"><a href="{% url 'costless:new-expense' %}">Enter new expense</a></p>
        <p class="link"><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>No costs are available.</p>
    {% endif %}
{% endblock %}

costless/templates/costless/expenses_by_user.html
{% extends "base.html" %}

{% block title %}Naslov{% endblock %}

{% block content %}
    <br>
    {% if latest_expenses_list %}
        <p class="link">Total: {{s}}</p>
        <table class = 'styled-table'>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Category</th>
                    <th>Subcategory</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for exp in latest_expenses_list %}
                    <tr>
                        <td>{{ exp.createdOn.date}}</td>
                        <td>{{ exp.createdOn|time}}</td>
                        <td><a href="{% url 'costless:category' exp.cat.catName %}">{{ exp.cat.catName}}</a> </td>
                        <td>{{ exp.subcat.subCatName}}</td>
                        <td>{{ exp.cost}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="link"><a href="{% url 'home' %}">Home</a></p>
        <p class="link"><a href="{% url 'costless:new-expense' %}">Enter new expense</a></p>
        <p class="link"><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>No costs are available.</p>
    {% endif %}
{% endblock %}

costless/templates/costless/newexpense.html
{% extends "base.html" %}

{% block content %}
  <br>
  <br>
  <form action="{% url 'costless:new-expense' %}" method="post" style=" width: 50vw; margin-left : 40vw;">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

costless/templates/costless/subcategory.html
{% extends "base.html" %}

{% block title %}Naslov{% endblock %}

{% block content %}
    {% if cat_list %}
        <p class="link"> Total for {{ level }}: {{all}} </p>
        <table class = 'styled-table'>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for exp in cat_list %}
                    <tr>
                        <td>{{ exp.createdOn.date}}</td>
                        <td>{{ exp.createdOn|time}}</td>
                        <td>{{ exp.cost}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="link"><a href="{% url 'home' %}">Home</a></p>
        <p class="link"><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>No costs are available.</p>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'costless/style.css' %}"> </link>
</head>
<body>
  <main>
    <img src="{% static 'costless/images/background.gif' %}" alt="Logo">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <br>
    <p class="link"> Hi {{ user.username }}! </p>

    <p class="link"><a href="{% url 'costless:new-expense' %}">Enter new expense</a></p>
    <p class="link"><a href="{% url 'costless:my-expenses' %}">All expenses</a></p>
    <p class="link"><a href="{% url 'costless:my-categories' %}">Expenses by categories</a></p>
    <p class="link"><a href="{% url 'costless:by-dates' %}">Expenses by dates</a></p>
    <p class="link"><a href="{% url 'logout' %}">Log Out</a></p>
    <p class="link"><a href="{% url 'password_reset' %}">Reset Password</a></p>
{% else %}
    <br>
    <p class="link">You are not logged in</p>
    <p class="link"><a href="{% url 'login' %}">Log In</a></p>
    <p class="link">or</p>
    <p class="link"><a href="{% url 'signup' %}">Sign Up</a></p>
{% endif %}
{% endblock %}